import Head from "next/head";
import { Headline } from "../src/components/Atoms/headline";
import { Button } from "../src/components/Atoms/button";
import { Link } from "../src/components/Atoms/link";

import buttonStyles from "../src/components/Atoms/button.module.css";
import linkStyles from "../src/components/Atoms/link.module.css";
import headlineStyles from "../src/components/Atoms/headline.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vanilla Extract</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="grid">
        <section className="gridElement">
          <Headline>Test</Headline>
          <p>
            Pellentesque habitant morbi tristique senectus et netus et malesuada
            fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
            ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
            egestas semper. Aenean ultricies mi vitae est. Mauris placerat
            eleifend leo.
          </p>
          <Headline tag="h4" className={headlineStyles.headlineSecondary}>
            Test
          </Headline>
          <p>
            Pellentesque habitant morbi tristique senectus et netus et malesuada
            fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
            ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
            egestas semper. Aenean ultricies mi vitae est. Mauris placerat
            eleifend leo.
          </p>
          <Headline tag="h5">Test</Headline>
          <p>
            Pellentesque habitant morbi tristique senectus et netus et malesuada
            fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
            ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
            egestas semper. Aenean ultricies mi vitae est. Mauris placerat
            eleifend leo.
          </p>
          <Headline tag="h6">Test</Headline>
          <p>
            Pellentesque habitant morbi tristique senectus et netus et malesuada
            fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
            ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
            egestas semper. Aenean ultricies mi vitae est. Mauris placerat
            eleifend leo.
          </p>
        </section>
        <section className="gridElement">
          <Headline tag="h2">HTML Ipsum Presents</Headline>
          <p>
            <strong>Pellentesque habitant morbi tristique</strong>
            senectus et netus et malesuada fames ac turpis egestas. Vestibulum
            tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
            Donec eu libero sit amet quam egestas semper.{" "}
            <em>Aenean ultricies mi vitae est.</em>
            Mauris placerat eleifend leo. Quisque sit amet est et sapien
            ullamcorper pharetra. Vestibulum erat wisi, condimentum sed,
            <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum,
            elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis
            tempus lacus enim ac dui. <a href="#">Donec non enim</a> in turpis
            pulvinar facilisis. Ut felis.
          </p>

          <h2>Header Level 2</h2>

          <ol>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Aliquam tincidunt mauris eu risus.</li>
          </ol>

          <blockquote>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              magna. Cras in mi at felis aliquet congue. Ut a est eget ligula
              molestie gravida. Curabitur massa. Donec eleifend, libero at
              sagittis mollis, tellus est malesuada tellus, at luctus turpis
              elit sit amet quam. Vivamus pretium ornare est.
            </p>
          </blockquote>

          <h3>Header Level 3</h3>

          <ul>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Aliquam tincidunt mauris eu risus.</li>
          </ul>
        </section>
        <section className="gridElement">
          <Headline>Elements</Headline>
          <p>
            <Link link="#internal">Link</Link>
          </p>
          <p>
            <Link
              design={linkStyles.linkSecondary}
              link="https://google.de"
              external
            >
              Link
            </Link>
          </p>
          <Button clickHandler={() => alert("TEST")}>Primary</Button>
          <Button
            design={buttonStyles.buttonSecondary}
            clickHandler={() => alert("TEST")}
          >
            Secondary
          </Button>
        </section>
      </main>
    </>
  );
}
